default_config:
lovelace:
  mode: yaml

automation:
  - alias: turn on bedroom light
    trigger:
      platform: state
      entity_id: binary_sensor.bedroom_door
      to: 'on'
    action:
      service: light.turn_on
      data_template:
        entity_id: light.bedroom
  - alias: turn off bedroom light
    trigger:
      platform: state
      entity_id: binary_sensor.bedroom_door
      to: 'off'
    action:
      service: light.turn_off
      data_template:
        entity_id: light.bedroom

yeelight:
  devices:
    192.168.xxx.xxx:
      name: Bedroom
