version: '3'
services:
  hass:
    image: homeassistant/home-assistant:0.113.3
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./static/configuration.yaml:/config/configuration.yaml:ro
      - ./static/ui-lovelace.yaml:/config/ui-lovelace.yaml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
